#pragma config(Motor,  port2,           FW1,           tmotorVex393, openLoop)
#pragma config(Motor,  port3,           FW2,           tmotorVex393, openLoop)
#pragma config(Motor,  port4,           FW3,           tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port5,           FW4,           tmotorVex393, openLoop, reversed)

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/* Flywheel program for 2 wheels, 4 motors (2 motors on each wheel
	Ports 4 and 5 reversed so the wheel spin outwards, in opposie directions. */

	// Working as of 11/23/2015

	//FW 1 AND 2 ARE LEFT, FW 3 AND 4 ARE RIGHT, FW1 IS FRONT
	// (when standing behind flywheel, shooting is front)

void Flywheel(int speed)
{
	motor[FW1] = speed;
	motor[FW2] = speed;
	motor[FW3] = speed;
	motor[FW4] = speed;
}

task main()
{
	while(true)
	{
		if(vexRT[Btn5U] == 1)
		{
			Flywheel(127);
		}
		else
		{
			Flywheel(0);
		}
	}
}
