#pragma config(Motor,  port2,           FW1,           tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port3,           FW2,           tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port4,           FW3,           tmotorVex393, openLoop)
#pragma config(Motor,  port5,           FW4,           tmotorVex393, openLoop)

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/* Flywheel program for 2 wheels, 4 motors (2 motors on each wheel
	Ports 2 and 3 reversed so wheels spin in opposite directions. */

	// Working as of 11/10/2015

void Flywheel(int speed)
{
	motor[FW1] = speed;
	motor[FW2] = speed;
	motor[FW3] = speed;
	motor[FW4] = speed;
}

task main()
{
	while(true)
	{
		if(vexRT[Btn5U] == 1)
		{
			Flywheel(127);
		}
		else
		{
			Flywheel(0);
		}
	}
}
