#pragma config(Motor,  port6,           FW1,           tmotorVex393, openLoop)
#pragma config(Motor,  port7,           FW2,           tmotorVex393, openLoop)
#pragma config(Motor,  port8,           FW3,           tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port9,           FW4,           tmotorVex393, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


void Flywheel(int speed)
{
	motor[FW1] = speed;
	motor[FW2] = speed;
	motor[FW3] = speed;
	motor[FW4] = speed;
}

bool fwmove = false;

/////////////////////////////////////////////////////////////////////

task main()
{
	while(true)
	{

		if (fwmove == false)
		{
			if (vexRT[Btn5U] == 1)
			{
				Flywheel(127);
				fwmove = true;
			}
		}


		if (fwmove == true)
		{
			if (vexRT[Btn5U] == 1)
			{
				Flywheel(127);
			}
			if (vexRT[Btn7U] == 1)
			{
				Flywheel(100);
			}
			else if (vexRT[Btn7L] == 1)
			{
				Flywheel(75);
			}
			else if (vexRT[Btn7D] == 1)
			{
				Flywheel(50);
			}
			else if (vexRT[Btn7R] == 1)
			{
				Flywheel(25);
			}
			else if (vexRT[Btn5D] == 1)
			{
				Flywheel(0);
				fwmove = false;
			}
		}
	}
}
