#pragma config(Motor,  port1,           DFR,           tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port2,           FW1,           tmotorVex393, openLoop)
#pragma config(Motor,  port3,           FW2,           tmotorVex393, openLoop)
#pragma config(Motor,  port4,           FW3,           tmotorVex393, openLoop)
#pragma config(Motor,  port5,           FW4,           tmotorVex393, openLoop)
#pragma config(Motor,  port6,           DBL,           tmotorVex393, openLoop)
#pragma config(Motor,  port7,           DBR,           tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port8,           conveyor,      tmotorVex393, openLoop)
#pragma config(Motor,  port9,           DMID,          tmotorVex393, openLoop)
#pragma config(Motor,  port10,          DFL,           tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/* Flywheel is front, intake is back.
Looking directly at the flywheel, ports 2 and 3 are left; ports 4 and 5 are right. */

void Flywheel(int speed)
{
	motor[FW1] = speed;
	motor[FW2] = speed;
	motor[FW3] = speed;
	motor[FW4] = speed;
}

task main()
{
	// FLYWHEEL VARIABLES ///////////////////////////////////////////////////////////////////////////////////////////
	// General threshold value.
	// "power" will be used to manipulate the flywheel's power while it is spinning.
	// Variable "x" used to gradually increase flywheel power in the first 0.35 seconds.
	// "flypower" is a manipulated value used to gradually reduce the flywheel's power when Button 5U is released.
	/////////////////////////////////////////////////////////////////////////////////////////////////////////////////

	int threshold = 20, power = 0, x = 0, f = 127, cont;
	float flypower = 127.0;

	// MECANUM DRIVE VARIABLES //////////////////////////////////////////////////////////////////////////////////////
	// [Left joystick, Y-axis] Ch3 = Y1 (Forward/Backward movement)
	// [Left joystick, X-axis] Ch4 = X1 (Srafe)
	// [Right joystick, X-axis] Ch1 = X2 (Rotation)
	////////////////////////////////////////////////////////////////////////////////////////////////////////////////

	int Y1 = 0, X1 = 0, X2 = 0;

	while(true)
	{
		// Flywheel //////////////////////////////////////////////////////////////////////////////////////
		//////////////////////////////////////////////////////////////////////////////////////////////////
		if((vexRT[Btn5U] == 1) && (motor[FW1] >= 65))
		{
			if(vexRT[Btn7U] == 1)
			{
				f = 127;
				Flywheel(f);
			}
			else if(vexRT[Btn7R] == 1)
			{
				f = 107;
				Flywheel(f);
			}
			else if(vexRT[Btn7D] == 1)
			{
				f = 87;
				Flywheel(f);
			}
			else if(vexRT[Btn7L] == 1)
			{
				f = 67;
				Flywheel(f);
			}
			else
			{
				cont = f;
				Flywheel(cont);
			}
		}
		// When Button 5U is pressed, flywheel starts at 60 power for 2.5 seconds.
		else if(vexRT[Btn5U] == 1)
		{
			x = x+12;
			Flywheel(x);
			wait1Msec(100);
		}

		// When Button 5U is released, flywheel's power is divided by 1.2 every 0.5 seconds.
		else if(motor[FW1] >= 8)
		{
			flypower = flypower/1.2;
			Flywheel(flypower);
			wait1Msec(500);
		}
		else
		{
			Flywheel(0);
			flypower = 127.0;
			power = 0;
			x = 0;
			f = 127;
			cont = 127;
		}


		// Mecanum Drive /////////////////////////////////////////////////////////////////////////
		//////////////////////////////////////////////////////////////////////////////////////////
		if(abs(vexRT[Ch3]) > threshold)
		{
			Y1 = vexRT[Ch3];
		}
		else
		{
			Y1 = 0;
		}

		if(abs(vexRT[Ch4]) > threshold)
		{
			X1 = vexRT[Ch4];
		}
		else
		{
			X1 = 0;
		}

		if(abs(vexRT[Ch1]) > threshold)
		{
			X2 = vexRT[Ch1];
		}
		else
		{
			X2 = 0;
		}
		//Remote Control Commands
		motor[DFR] = Y1 - X2 - X1;
		motor[DBR] =  Y1 - X2 + X1;
		motor[DFL] = Y1 + X2 + X1;
		motor[DBL] =  Y1 + X2 - X1;
	}
}
