#pragma config(Motor,  port2,           port2,         tmotorVex393, openLoop)
#pragma config(Motor,  port3,           port3,         tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port4,           port4,         tmotorVex393, openLoop)
#pragma config(Motor,  port5,           port5,         tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void dankmemes(int a)
{
	motor[port2] = a;
	motor[port3] = a;
	motor[port4] = a;
	motor[port5] = a;
}

task main()
{
	while(true)
	{
		if(vexRT[Btn7U] == 1)
		{
			dankmemes(127);
		}
		else
		{
			dankmemes(0);
		}
	}


}
