#pragma config(Motor,  port2,           DFR,           tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port3,           DBR,           tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port4,           DFL,           tmotorVex393, openLoop)
#pragma config(Motor,  port5,           DBL,           tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
[Left joystick, Y-axis] Ch3 = Y1 (Forward/Backward movement)
[Left joystick, X-axis] Ch4 = X1 (Srafe)
[Right joystick, X-axis] Ch1 = X2 (Rotation)

/* Holonomic: for DFR/DBR/DFL/DBL...
		Intake1 is bottom, Intake2 is right

		DFR and DBR  have been reversed in this program.	*/

// Working as of 11/10/2015


task main()
{
	int Y1 = 0, X1 = 0, X2 = 0, threshold = 20;
	while(true)
	{
		if(abs(vexRT[Ch3]) > threshold)
		{
			Y1 = vexRT[Ch3];
		}
		else
		{
			Y1 = 0;
		}

		if(abs(vexRT[Ch4]) > threshold)
		{
			X1 = vexRT[Ch4];
		}
		else
		{
			X1 = 0;
		}

		if(abs(vexRT[Ch1]) > threshold)
		{
			X2 = vexRT[Ch1];
		}
		else
		{
			X2 = 0;
		}

		//Remote Control Commands (equations diff. for other holonomic program)
		motor[DFR] = Y1 - X2 - X1;
		motor[DBR] =  Y1 - X2 + X1;
		motor[DFL] = Y1 + X2 + X1;
		motor[DBL] =  Y1 + X2 - X1;
	}
}
