#pragma config(Sensor, in1,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl1,  RB1,            sensorQuadEncoder)
#pragma config(Motor,  port1,           in1,           tmotorVex393, openLoop)
#pragma config(Motor,  port2,           FW1,           tmotorVex393, openLoop)
#pragma config(Motor,  port3,           FW2,           tmotorVex393, openLoop)
#pragma config(Motor,  port4,           DFL,           tmotorVex393, openLoop)
#pragma config(Motor,  port5,           DBL,           tmotorVex393, openLoop)
#pragma config(Motor,  port6,           DFR,           tmotorVex393, openLoop)
#pragma config(Motor,  port7,           DBR,           tmotorVex393, openLoop)
#pragma config(Motor,  port8,           FW3,           tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port9,           FW4,           tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port10,          in2,           tmotorVex393, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/* 12/21/15

// COMPETITION PROGRAM

// TO DO: Find a way to implement conveyor that will allow the ball to incline up the flywheel
(Power expander needed?)
i
HOW TO SET UP PORTS :

FW1 is front left, FW4 IS back right.
(when standing behind flywheel, shooting is front) if yo uneed me, text 562-889-4304 and sign ur name at the end

Holonomic drive: for DFR/DBR/DFL/DBL...
in1 is bottom, in2 is right.

FW3 and FW4 are reversed so flywheel can shoot.
in2 is reversed so intakes move in same direction.
DFR and DBR reversed so robot moves in correct directions. */




#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////////
////////// FUNCTIONS ////////////////////////////////////////////////////////////////////////

bool fwmove = false;

void Flywheel(int speed)
{
	motor[FW1] = speed;
	motor[FW2] = speed;
	motor[FW3] = speed;
	motor[FW4] = speed;
}


void intake (int speed)
{
	motor[in1] = speed;
	motor[in2] = speed;
}

void driveStraight(int speed)
{
	motor[DFR] = speed;
	motor[DBR] = speed;
	motor[DBL] = speed;
	motor[DFL] = speed;
}

void checkSensorValue(int distance, int speed)
{
	while(SensorValue(RB1) < distance)
	{
		driveStraight(speed);
	}
}

void gyroTurn(int degrees)
{
	int gyroDrift = 10;
	while(abs(SensorValue[gyro]) > degrees + gyroDrift || abs(SensorValue[gyro]) < degrees - gyroDrift)
	{
		if(abs(SensorValue[gyro]) > degrees)
		{
			motor[DBR] = 40;
			motor[DBL] = 40;
			motor[DFR] = 40;
			motor[DFL] = 40;
		}
		else
		{

		}
	}
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
	// Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is   used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
	/*
	Autonomous 1: Spin the Flywheel, then move
	Flywheel(127);
	//confirm that ball has been launched
	checkSensorValue(some distance, 127);

	*/

	/*
	Autonomous 2: run forward and try to control some of the balls on the floor
	motor[conveyor] = 100;
	checkSensorValue(500,127);
	gyroTurn(420);


	*/
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////



task usercontrol()
{
	int threshold = 20;

	// MECANUM DRIVE VARIABLES /////////////////////////////////////////////////////////////////////////
	// [Left joystick, Y-axis] Ch3 = Y1 (Forward/Backward movement)
	// [Left joystick, X-axis] Ch4 = X1 (Srafe)
	// [Right joystick, X-axis] Ch1 = X2 (Rotation)

	int Y1 = 0, X1 = 0, X2 = 0;

	while(true)
	{
		// Flywheel //////////////////////////////////////////////////////////////////////////////////////
		//////////////////////////////////////////////////////////////////////////////////////////////////

		if (vexRT[Btn5U] == 1)
		{
			Flywheel(127);

		}
		else
		{
			Flywheel(0);
		}



		// Mecanum Drive /////////////////////////////////////////////////////////////////////////
		//////////////////////////////////////////////////////////////////////////////////////////
		if(abs(vexRT[Ch3]) > threshold)
		{
			Y1 = vexRT[Ch3];
		}
		else
		{
			Y1 = 0;
		}

		if(abs(vexRT[Ch4]) > threshold)
		{
			X1 = vexRT[Ch4];
		}
		else
		{
			X1 = 0;
		}

		if(abs(vexRT[Ch1]) > threshold)
		{
			X2 = vexRT[Ch1];
		}
		else
		{
			X2 = 0;
		}
		//Remote Control Commands
		motor[DFR] = Y1 - X2 - X1;
		motor[DBR] =  Y1 - X2 + X1;
		motor[DFL] = Y1 + X2 + X1;
		motor[DBL] =  Y1 + X2 - X1;

		// Intake ////////////////////////////////////////////////////////////////////////////////////////
		//////////////////////////////////////////////////////////////////////////////////////////////////
		if(vexRT[Btn6U] == 1)
		{
			intake(127);
		}
		else if(vexRT[Btn6D] == 1)
		{
			intake(-127);
		}
		else
		{
			intake(0);
		}
	}
}
